// 데모 리포트 정적 데이터
// report.json 기반, access_level: "standard", overlay/hair_simulation/paywall/payment_account 제외

import type { ReportData } from "@/lib/types/report";

export const DEMO_REPORT: ReportData = {
  id: "report_abcc2bea",
  user_name: "Dami",
  access_level: "standard",
  pending_level: null,
  sections: [
    {
      id: "cover",
      locked: false,
      content: {
        title: "시각 리포트",
        user_name: "Dami",
        date: "2026-04-15",
        tier: "standard",
      },
    },
    {
      id: "executive_summary",
      locked: false,
      content: {
        summary:
          "현재 부드러운 카리스마 타입이지만 더 발랄하고 어린 느낌으로 변화를 추구하시는군요. 송하영처럼 자연스럽고 사랑스러운 이미지를 만들기 위해 볼 사과존 블러셔와 자연스러운 립 톤이 핵심이에요. 여름 라이트 타입이니 컬러는 쿨톤 베이스의 밝고 부드러운 계열로 잡으세요. 2026 S/S 트렌드인 '도도한 동안'과도 완벽하게 맞아떨어져요.",
      },
    },
    {
      id: "face_structure",
      locked: false,
      content: {
        face_type: "타원형",
        face_length_ratio: 1.347000002861023,
        jaw_angle: 107.8,
        symmetry_label: "대칭 보통 수준",
        golden_ratio_label: "황금비 높은 편",
        metrics: [
          {
            key: "jaw_angle",
            label: "턱 각도",
            value: 107.8,
            unit: "\u00B0",
            percentile: 68,
            context: "평균(102.92\u00B0) 대비 넓은 편 — 부드러운 라인",
            min_value: 85,
            max_value: 125,
            min_label: "날카로운",
            max_label: "둥근",
            show_numeric_value: false,
            context_label: "107.8\u00B0",
          },
          {
            key: "face_length_ratio",
            label: "얼굴 종횡비",
            value: 1.347,
            unit: "",
            percentile: 95,
            context: "표준 타원형 범위(1.3-1.5)",
            min_value: 1.1,
            max_value: 1.35,
            min_label: "넓은",
            max_label: "긴",
            show_numeric_value: false,
            context_label: "매우 높은 편",
          },
          {
            key: "symmetry_score",
            label: "좌우 대칭도",
            value: 0.929,
            unit: "",
            percentile: 55,
            context: "보통 수준",
            min_value: 0.6,
            max_value: 1,
            min_label: "비대칭",
            max_label: "대칭",
            show_numeric_value: false,
            context_label: "보통 수준",
          },
          {
            key: "golden_ratio_score",
            label: "황금비 근접도",
            value: 0.835,
            unit: "",
            percentile: 81,
            context: "조화로운 비율",
            min_value: 0.65,
            max_value: 0.9,
            min_label: "낮음",
            max_label: "황금비",
            show_numeric_value: false,
            context_label: "높은 편",
          },
          {
            key: "cheekbone_prominence",
            label: "광대 돌출도",
            value: 0.611,
            unit: "",
            percentile: 42,
            context: "돌출된 편",
            min_value: 0.4,
            max_value: 0.85,
            min_label: "평면",
            max_label: "돌출",
            show_numeric_value: false,
            context_label: "보통 수준",
          },
        ],
        interpretation_unlock_level: "standard",
        overall_impression:
          "전체적으로 균형 잡힌 타원형 얼굴로, 부드럽고 온화한 인상을 주는 구조예요. 높은 대칭성과 황금비에 근접한 비율로 자연스러운 조화를 이루고 있어요.",
        feature_interpretations: [
          {
            feature: "jaw_angle",
            label: "턱선",
            value: 107.8,
            unit: "\u00B0",
            percentile: 68,
            range_label: "상위 32%",
            interpretation:
              "둥글고 부드러운 턱선으로 친근하고 온화한 인상을 만들어요. 각진 느낌보다는 곡선미가 두드러져서 여성스럽고 부드러운 이미지를 줘요.",
            min_label: "날카로운",
            max_label: "둥근",
            show_numeric_value: false,
            context_label: "107.8\u00B0",
          },
          {
            feature: "cheekbone_prominence",
            label: "광대",
            value: 0.611,
            unit: "",
            percentile: 42,
            range_label: "하위 42%",
            interpretation:
              "적당히 발달한 광대로 얼굴에 입체감을 더해요. 너무 돌출되지 않아서 자연스러우면서도 구조적인 아름다움을 보여줘요.",
            min_label: "평면",
            max_label: "돌출",
            show_numeric_value: false,
            context_label: "보통 수준",
          },
          {
            feature: "eye_tilt",
            label: "눈꼬리 기울기",
            value: 2.75,
            unit: "\u00B0",
            percentile: 56,
            range_label: "상위 44%",
            interpretation:
              "살짝 올라간 눈꼬리로 생동감 있고 매력적인 인상을 연출해요. 처지지 않아서 활기차고 젊은 느낌을 줘요.",
            min_label: "처진",
            max_label: "올라간",
            show_numeric_value: false,
            context_label: "2.8\u00B0",
          },
          {
            feature: "nose_bridge_height",
            label: "코 높이",
            value: 0.494,
            unit: "",
            percentile: 27,
            range_label: "하위 27%",
            interpretation:
              "적당한 높이의 콧대로 자연스럽고 균형 잡힌 옆모습을 만들어요. 과하지 않아서 전체적인 조화를 해치지 않아요.",
            min_label: "낮음",
            max_label: "높음",
            show_numeric_value: false,
            context_label: "다소 낮은 편",
          },
          {
            feature: "symmetry_score",
            label: "대칭도",
            value: 0.929,
            unit: "",
            percentile: 55,
            range_label: "상위 45%",
            interpretation:
              "매우 높은 대칭성으로 안정되고 균형 잡힌 인상을 줘요. 좌우 균형이 잘 맞아서 시각적으로 편안하고 아름다운 인상을 만들어요.",
            min_label: "비대칭",
            max_label: "대칭",
            show_numeric_value: false,
            context_label: "보통 수준",
          },
          {
            feature: "golden_ratio_score",
            label: "황금비",
            value: 0.835,
            unit: "",
            percentile: 81,
            range_label: "상위 19%",
            interpretation:
              "황금비에 가까운 비율로 자연스럽고 조화로운 얼굴 구조를 보여줘요. 각 부위의 크기와 위치가 이상적인 균형을 이루고 있어요.",
            min_label: "낮음",
            max_label: "황금비",
            show_numeric_value: false,
            context_label: "높은 편",
          },
        ],
        harmony_note:
          "부드러운 곡선과 높은 대칭성이 어우러져 자연스럽고 편안한 아름다움을 완성하고 있어요.",
        distinctive_points: [
          "부드러운 타원형 얼굴",
          "높은 대칭도와 균형감",
          "온화하고 친근한 전체 인상",
        ],
      },
    },
    {
      id: "skin_analysis",
      locked: true,
      unlock_level: "standard",
      teaser: {
        headline: "여름 라이트",
      },
      content: {
        tone: "여름 라이트",
        tone_description:
          "밝고 청량한 쿨톤이에요. 부드러운 파스텔 핑크 계열이 자연스럽게 어울려요.",
        hex_sample: "#8E796E",
        best_colors: [
          {
            name: "로즈 핑크",
            hex: "#FF66B2",
            usage: "립",
            why: "쿨한 피부톤을 맑고 화사하게 살려줘요.",
          },
          {
            name: "베이비 핑크",
            hex: "#F4C2C2",
            usage: "립",
            why: "파스텔 톤이 밝은 피부와 자연스럽게 녹아요.",
          },
          {
            name: "라벤더 핑크",
            hex: "#D8A0D8",
            usage: "포인트",
            why: "쿨 언더톤을 살리면서 고급스러운 느낌을 줘요.",
          },
        ],
        okay_colors: [
          {
            name: "쿨 누드",
            hex: "#D2B4A0",
            usage: "베이스",
            why: "무난하고 편안한 데일리 톤이에요.",
          },
          {
            name: "소프트 레드",
            hex: "#C74375",
            usage: "포인트",
            why: "강한 포인트가 필요할 때 쿨 베이스로 활용해요.",
          },
        ],
        avoid_colors: [
          {
            name: "오렌지",
            hex: "#FF8C00",
            why: "따뜻한 색이 쿨한 피부에서 떠요.",
          },
          {
            name: "브릭",
            hex: "#CB4154",
            why: "탁한 웜 계열이 피부를 칙칙하게 만들어요.",
          },
          {
            name: "테라코타",
            hex: "#E2725B",
            why: "흙빛 웜톤이 청량한 피부와 충돌해요.",
          },
        ],
        recommended: [
          {
            name: "로즈 핑크",
            hex: "#FF66B2",
            usage: "립",
            why: "쿨한 피부톤을 맑고 화사하게 살려줘요.",
          },
          {
            name: "베이비 핑크",
            hex: "#F4C2C2",
            usage: "립",
            why: "파스텔 톤이 밝은 피부와 자연스럽게 녹아요.",
          },
          {
            name: "라벤더 핑크",
            hex: "#D8A0D8",
            usage: "포인트",
            why: "쿨 언더톤을 살리면서 고급스러운 느낌을 줘요.",
          },
        ],
        avoid: [
          {
            name: "오렌지",
            hex: "#FF8C00",
            why: "따뜻한 색이 쿨한 피부에서 떠요.",
          },
          {
            name: "브릭",
            hex: "#CB4154",
            why: "탁한 웜 계열이 피부를 칙칙하게 만들어요.",
          },
          {
            name: "테라코타",
            hex: "#E2725B",
            why: "흙빛 웜톤이 청량한 피부와 충돌해요.",
          },
        ],
        avoid_reason: "따뜻한 색이 쿨한 피부에서 떠요.",
        hair_colors: [
          {
            name: "애쉬 블론드",
            hex: "#B8A590",
            why: "쿨한 피부톤에 투명한 느낌을 더해요.",
          },
          {
            name: "라벤더 그레이",
            hex: "#9C8FA3",
            why: "쿨 언더톤을 극대화하는 트렌디한 컬러예요.",
          },
          {
            name: "쿨 베이지 브라운",
            hex: "#A09080",
            why: "자연스러우면서도 칙칙하지 않은 중간 톤이에요.",
          },
        ],
        season: "summer",
        subtype: "light",
        lip_direction:
          "차갑고 밝은 핑크 계열. 부드럽게 한 겹 올리는 느낌으로.",
        cheek_direction: "청량한 핑크빛 혈색. 피부 속 투명감을 살려요.",
        eye_direction: "시원한 톤의 명색. 펄은 실버/핑크 펄.",
        foundation_guide: "13~17호 쿨 (13C, 17C)",
        confidence: 0.13,
        _undertone: "neutral",
        _chroma: 10.9,
        _warmth: 12.1,
        _brightness: 0.519,
      },
    },
    {
      id: "gap_analysis",
      locked: true,
      unlock_level: "standard",
      teaser: {
        headline: "부드러운 카리스마 \u2192 따뜻한 첫사랑",
      },
      content: {
        current_type: "부드러운 카리스마",
        current_type_id: 6,
        aspiration_type: "따뜻한 첫사랑",
        aspiration_type_id: 1,
        aspiration_description:
          "둥근 얼굴형, 부드러운 턱선, 큰 둥근 눈, 도톰한 입술. 작은 이목구비에 어린 비율. 따뜻하고 부드러운 인상.",
        aspiration_features: [
          "둥근 얼굴형",
          "부드러운 턱선",
          "큰 둥근 눈",
          "도톰한 입술",
          "작은 이목구비에 어린 비율",
          "따뜻하고 부드러운 인상",
        ],
        current_coordinates: {
          shape: -0.15,
          volume: 0.18,
          age: 0.34,
        },
        aspiration_coordinates: {
          shape: -0.7,
          volume: -0.6,
          age: -0.7,
        },
        gap_magnitude: 1.41,
        gap_difficulty: "큰 변화",
        gap_summary:
          "가장 큰 변화는 더 발랄한 방향으로 가는 거예요. 그리고 전체적으로 더 은은한 느낌으로요.",
        direction_items: [
          {
            axis: "age",
            label: "무드",
            name_kr: "무드",
            label_low: "발랄한",
            label_high: "성숙한",
            axis_description: "전체적인 분위기의 방향",
            from_score: 0.34,
            to_score: -0.7,
            delta: 1.04,
            from_label: "약간 성숙한",
            to_label: "발랄한 방향으로",
            difficulty: "큰 변화",
            recommendation:
              "무드에서는 어려 보이고 생기 있는 느낌을 더하는 방향이 잘 맞아요.",
          },
          {
            axis: "volume",
            label: "존재감",
            name_kr: "존재감",
            label_low: "은은한",
            label_high: "강렬한",
            axis_description: "이목구비의 선명도",
            from_score: 0.18,
            to_score: -0.6,
            delta: 0.78,
            from_label: "약간 강렬한",
            to_label: "은은한 방향으로",
            difficulty: "큰 변화",
            recommendation:
              "존재감에서는 자연스럽고 힘을 뺀 표현이 포인트예요.",
          },
          {
            axis: "shape",
            label: "골격",
            name_kr: "골격",
            label_low: "부드러운",
            label_high: "또렷한",
            axis_description: "턱선, 광대, 눈매가 만드는 골격의 형태",
            from_score: -0.15,
            to_score: -0.7,
            delta: 0.55,
            from_label: "약간 부드러운",
            to_label: "부드러운 방향으로",
            difficulty: "큰 변화",
            recommendation:
              "골격에서는 윤곽을 둥글고 부드럽게 풀어주는 방향이 핵심이에요.",
          },
        ],
        aesthetic_map: {
          current: {
            x: -0.15,
            y: 0.34,
            size: 0.18,
          },
          aspiration: {
            x: -0.7,
            y: -0.7,
            size: -0.6,
          },
          x_axis: {
            name_kr: "골격",
            low: "부드러운",
            high: "또렷한",
            low_en: "Soft",
            high_en: "Sharp",
            description: "턱선, 광대, 눈매가 만드는 골격의 형태",
          },
          y_axis: {
            name_kr: "무드",
            low: "발랄한",
            high: "성숙한",
            low_en: "Fresh",
            high_en: "Mature",
            description: "전체적인 분위기의 방향",
          },
          size_axis: {
            name_kr: "존재감",
            low: "은은한",
            high: "강렬한",
            low_en: "Subtle",
            high_en: "Bold",
            description: "이목구비의 선명도",
          },
          quadrants: {
            top_left: "Soft Mature",
            top_right: "Sharp Mature",
            bottom_left: "Soft Fresh",
            bottom_right: "Sharp Fresh",
          },
          description:
            "가로축은 골격의 형태, 세로축은 분위기의 방향이에요. 점이 클수록 이목구비 선명도가 높아요.",
        },
        trend: {
          x: 0.09,
          y: -0.13,
          size: 0.07,
        },
      },
    },
  ],
};
