import type { ReportData } from "@/lib/types/report";

// 실제 리포트 기반 목 데이터 (access_level: full — 전체 섹션 표시)
export const MOCK_REPORT: ReportData = {
  id: "report_mock_001",
  user_name: "김시각",
  access_level: "full",
  pending_level: null,
  sections: [
    {
      id: "cover",
      locked: false,
      content: {
        title: "시각 리포트",
        user_name: "김시각",
        date: "2026-04-13",
        tier: "full",
      },
    },
    {
      id: "executive_summary",
      locked: false,
      content: {
        summary:
          "부드럽고 조화로운 타원형 얼굴로, 전체적으로 균형 잡힌 인상을 보여줘요. 높은 대칭성과 황금비에 가까운 비율이 자연스럽고 안정적인 느낌을 만들어내고 있어요.",
      },
    },
    {
      id: "face_structure",
      locked: false,
      content: {
        face_type: "타원형",
        face_length_ratio: 1.385,
        jaw_angle: 107.2,
        symmetry_score: 0.968,
        golden_ratio_score: 0.834,
        metrics: [
          {
            key: "jaw_angle",
            label: "턱 각도",
            value: 107.2,
            unit: "\u00B0",
            percentile: 66,
            context: "평균(102\u00B0) 대비 넓은 편 \u2014 부드러운 라인",
            min_value: 85,
            max_value: 125,
            min_label: "날카로운",
            max_label: "둥근",
            show_numeric_value: false,
            context_label: "107.2\u00B0",
          },
          {
            key: "face_length_ratio",
            label: "얼굴 종횡비",
            value: 1.385,
            unit: "",
            percentile: 95,
            context: "표준 타원형 범위(1.3-1.5)",
            min_value: 1.1,
            max_value: 1.35,
            min_label: "넓은",
            max_label: "긴",
            show_numeric_value: false,
            context_label: "매우 높은 편",
          },
          {
            key: "symmetry_score",
            label: "좌우 대칭도",
            value: 0.968,
            unit: "",
            percentile: 72,
            context: "균형 잡힌 구조",
            min_value: 0.6,
            max_value: 1,
            min_label: "비대칭",
            max_label: "대칭",
            show_numeric_value: false,
            context_label: "다소 높은 편",
          },
          {
            key: "golden_ratio_score",
            label: "황금비 근접도",
            value: 0.834,
            unit: "",
            percentile: 81,
            context: "조화로운 비율",
            min_value: 0.65,
            max_value: 0.9,
            min_label: "낮음",
            max_label: "황금비",
            show_numeric_value: false,
            context_label: "높은 편",
          },
          {
            key: "cheekbone_prominence",
            label: "광대 돌출도",
            value: 0.625,
            unit: "",
            percentile: 49,
            context: "돌출된 편",
            min_value: 0.4,
            max_value: 0.85,
            min_label: "평면",
            max_label: "돌출",
            show_numeric_value: false,
            context_label: "보통 수준",
          },
        ],
        interpretation_unlock_level: "standard",
        overall_impression:
          "부드럽고 조화로운 타원형 얼굴로, 전체적으로 균형 잡힌 인상을 보여줘요. 높은 대칭성과 황금비에 가까운 비율이 자연스럽고 안정적인 느낌을 만들어내고 있어요.",
        feature_interpretations: [
          {
            feature: "jaw_angle",
            label: "턱선",
            value: 107.2,
            unit: "\u00B0",
            percentile: 66,
            range_label: "상위 34%",
            interpretation:
              "부드러운 턱선이 온화하고 친근한 인상을 만들어줘요. 각진 느낌보다는 자연스러운 곡선미가 돋보이는 편이에요.",
            min_label: "날카로운",
            max_label: "둥근",
            show_numeric_value: false,
            context_label: "107.2\u00B0",
          },
          {
            feature: "cheekbone_prominence",
            label: "광대",
            value: 0.625,
            unit: "",
            percentile: 49,
            range_label: "하위 49%",
            interpretation:
              "광대가 적당히 뚜렷한 편이라 얼굴에 입체감을 더해주면서도 과하지 않아 자연스러운 볼륨감을 연출해요.",
            min_label: "평면",
            max_label: "돌출",
            show_numeric_value: false,
            context_label: "보통 수준",
          },
          {
            feature: "eye_width_ratio",
            label: "눈 크기",
            value: 0.192,
            unit: "",
            percentile: 47,
            range_label: "하위 47%",
            interpretation:
              "눈이 전체적으로 아담한 편이라 섬세하고 차분한 인상을 줘요. 얼굴 전체와의 조화가 잘 맞아 균형감이 좋아요.",
            min_label: "작은",
            max_label: "큰",
            show_numeric_value: false,
            context_label: "보통 수준",
          },
          {
            feature: "eye_tilt",
            label: "눈꼬리 기울기",
            value: 2.66,
            unit: "\u00B0",
            percentile: 55,
            range_label: "상위 45%",
            interpretation:
              "눈꼬리가 살짝 올라간 편이라 생기 있고 활기찬 인상을 만들어줘요. 자연스러운 미소 같은 느낌을 연출해요.",
            min_label: "처진",
            max_label: "올라간",
            show_numeric_value: false,
            context_label: "2.7\u00B0",
          },
          {
            feature: "symmetry_score",
            label: "대칭도",
            value: 0.968,
            unit: "",
            percentile: 72,
            range_label: "상위 28%",
            interpretation:
              "얼굴 대칭성이 매우 뛰어나 안정적이고 조화로운 인상을 줘요. 자연스러우면서도 정돈된 느낌이 강해요.",
            min_label: "비대칭",
            max_label: "대칭",
            show_numeric_value: false,
            context_label: "다소 높은 편",
          },
          {
            feature: "golden_ratio_score",
            label: "황금비",
            value: 0.834,
            unit: "",
            percentile: 81,
            range_label: "상위 19%",
            interpretation:
              "황금비에 상당히 근접한 비율로 시각적으로 편안하고 아름다운 인상을 만들어내요. 자연스러운 균형감이 돋보여요.",
            min_label: "낮음",
            max_label: "황금비",
            show_numeric_value: false,
            context_label: "높은 편",
          },
        ],
        harmony_note:
          "높은 대칭성과 황금비 근접성이 만들어내는 자연스러운 조화가 전체적으로 편안하고 안정적인 인상을 완성해요.",
        distinctive_points: [
          "매우 높은 대칭성으로 정돈되고 균형 잡힌 인상",
          "황금비에 가까운 비율로 자연스러운 아름다움",
          "부드러운 턱선과 적당한 광대가 만드는 온화한 느낌",
        ],
      },
    },
    {
      id: "skin_analysis",
      locked: false,
      unlock_level: "standard",
      teaser: { headline: "가을 딥" },
      content: {
        tone: "가을 딥",
        tone_description:
          "깊고 풍부한 웜톤이에요. 진하고 무게감 있는 색이 잘 소화되는 경향이 있어요.",
        hex_sample: "#6F4F3C",
        recommended: [
          { name: "버건디", hex: "#800020", usage: "립" },
          { name: "딥 브라운 레드", hex: "#6B3A2A", usage: "립" },
          { name: "다크 코랄", hex: "#C04040", usage: "립" },
          { name: "와인", hex: "#722F37", usage: "포인트" },
          { name: "초콜릿", hex: "#7B3F00", usage: "포인트" },
        ],
        avoid: [
          { name: "파스텔 핑크", hex: "#FFD1DC" },
          { name: "라벤더", hex: "#B57EDC" },
          { name: "네온", hex: "#39FF14" },
        ],
        avoid_reason:
          "가볍고 밝은 파스텔이 피부톤과 분리되어 보일 수 있어요.",
        season: "autumn",
        subtype: "deep",
        lip_direction: "깊고 진한 웜 계열. 무게감 있는 발색.",
        cheek_direction: "깊은 혈색. 피부와 대비 살리기.",
        eye_direction: "깊은 어스톤. 스모키에 강함.",
        foundation_guide: "25~27호 웜 (25W, 27W)",
        confidence: 0.07,
        _undertone: "warm",
        _chroma: 18.5,
        _warmth: 20.6,
        _brightness: 0.355,
      },
    },
    {
      id: "gap_analysis",
      locked: false,
      unlock_level: "standard",
      teaser: { headline: "부드러운 카리스마 \u2192 날카로운 카리스마" },
      content: {
        current_type: "부드러운 카리스마",
        current_type_id: 6,
        aspiration_type: "날카로운 카리스마",
        aspiration_type_id: 8,
        aspiration_description:
          "긴 각진 얼굴, 강한 턱선. 크고 날카로운 눈, 두꺼운 입술, 높은 코. 성숙한 비율에 압도적인 존재감. 강렬한 카리스마.",
        aspiration_features: [
          "긴 각진 얼굴",
          "강한 턱선",
          "크고 날카로운 눈",
          "두꺼운 입술",
          "높은 코",
          "성숙한 비율에 압도적인 존재감",
          "강렬한 카리스마",
        ],
        current_coordinates: { shape: -0.07, volume: 0.27, age: 0.15 },
        aspiration_coordinates: { shape: 0.6, volume: 0.4, age: 0.3 },
        gap_magnitude: 0.7,
        gap_difficulty: "작은 변화",
        gap_summary:
          "가장 큰 변화는 더 또렷한 방향으로 가는 거예요. 그리고 전체적으로 더 성숙한 느낌으로요.",
        direction_items: [
          {
            axis: "shape",
            label: "골격",
            name_kr: "골격",
            label_low: "부드러운",
            label_high: "또렷한",
            axis_description:
              "턱선, 광대, 눈매가 만드는 골격의 형태",
            from_score: -0.07,
            to_score: 0.6,
            delta: 0.67,
            from_label: "중간",
            to_label: "또렷한 방향으로",
            difficulty: "큰 변화",
            recommendation:
              "골격에서는 좀 더 선명하고 또렷한 윤곽을 만드는 방향이 핵심이에요.",
          },
          {
            axis: "age",
            label: "무드",
            name_kr: "무드",
            label_low: "발랄한",
            label_high: "성숙한",
            axis_description:
              "전체적인 분위기의 방향",
            from_score: 0.15,
            to_score: 0.3,
            delta: 0.15,
            from_label: "중간",
            to_label: "성숙한 방향으로",
            difficulty: "작은 변화",
            recommendation:
              "무드에서는 세련되고 성숙한 느낌을 더하는 방향이에요.",
          },
          {
            axis: "volume",
            label: "존재감",
            name_kr: "존재감",
            label_low: "은은한",
            label_high: "강렬한",
            axis_description:
              "이목구비의 선명도",
            from_score: 0.27,
            to_score: 0.4,
            delta: 0.13,
            from_label: "약간 강렬한",
            to_label: "거의 일치",
            difficulty: "거의 일치",
            recommendation:
              "존재감은 현재와 추구미가 거의 같아요. 지금 방향 그대로 좋아요.",
          },
        ],
        aesthetic_map: {
          current: { x: -0.07, y: 0.15, size: 0.27 },
          aspiration: { x: 0.6, y: 0.3, size: 0.4 },
          x_axis: {
            name_kr: "골격",
            low: "부드러운",
            high: "또렷한",
            low_en: "Soft",
            high_en: "Sharp",
            description: "턱선, 광대, 눈매가 만드는 골격의 형태",
          },
          y_axis: {
            name_kr: "무드",
            low: "발랄한",
            high: "성숙한",
            low_en: "Fresh",
            high_en: "Mature",
            description: "전체적인 분위기의 방향",
          },
          size_axis: {
            name_kr: "존재감",
            low: "은은한",
            high: "강렬한",
            low_en: "Subtle",
            high_en: "Bold",
            description: "이목구비의 선명도",
          },
          quadrants: {
            top_left: "Soft Mature",
            top_right: "Sharp Mature",
            bottom_left: "Soft Fresh",
            bottom_right: "Sharp Fresh",
          },
          description:
            "가로축은 골격의 형태, 세로축은 분위기의 방향이에요. 점이 클수록 이목구비 선명도가 높아요.",
        },
        trend_coordinates: null,
        gap_to_trend: null,
        blend_weights: null,
      },
    },
    {
      id: "hair_recommendation",
      locked: false,
      unlock_level: "full",
      teaser: {
        headline: "비대칭 사이드뱅 + 보브단발/단발 레이어드컷.",
      },
      content: {
        cheat_sheet: "비대칭 사이드뱅 + 보브단발/단발 레이어드컷.",
        top_combos: [
          {
            rank: 1,
            score: 0.95,
            front: {
              id: "h-f04",
              name_kr: "비대칭 사이드뱅",
              name_en: "Asymmetric Side Bangs",
              image: "/assets/reference/hair/front/h-f04.jpg",
            },
            back: {
              id: "h-b02",
              name_kr: "보브단발/레이어드",
              name_en: "Bob Cut / Layered",
              image_front: "/assets/reference/hair/back-front/h-b02.png",
              image_rear: "/assets/reference/hair/back-rear/h-b02.jpg",
            },
            why: "비대칭이라 턱 부각 덜함. 층으로 턱 옆 무게감 감소. 비대칭 앞머리 + 가벼운 뒷머리 = 시원하고 세련된 조화.",
            axis_shift: {},
            salon_instruction: "목 중간보다 길어지지 않도록.",
            trend: null,
          },
          {
            rank: 2,
            score: 0.95,
            front: {
              id: "h-f04",
              name_kr: "비대칭 사이드뱅",
              name_en: "Asymmetric Side Bangs",
              image: "/assets/reference/hair/front/h-f04.jpg",
            },
            back: {
              id: "h-b12",
              name_kr: "긴머리 레이어드펌",
              name_en: "Long Layered Perm",
              image_front: "/assets/reference/hair/back-front/h-b12.jpg",
              image_rear: "/assets/reference/hair/back-rear/h-b12.png",
            },
            why: "비대칭이라 턱 부각 덜함. 레이어드로 턱 아래 무게감 감소. 비대칭 앞머리 + 가벼운 뒷머리 = 시원하고 세련된 조화.",
            axis_shift: {},
            salon_instruction:
              "C컬은 쇄골보다 2-3cm 아래에 레이어드, 목 주변 컬 아주 굵게.",
            trend: null,
          },
          {
            rank: 3,
            score: 0.8,
            front: {
              id: "h-f04",
              name_kr: "비대칭 사이드뱅",
              name_en: "Asymmetric Side Bangs",
              image: "/assets/reference/hair/front/h-f04.jpg",
            },
            back: {
              id: "h-b07",
              name_kr: "중단발 레이어드",
              name_en: "Medium Layered",
              image_front: "/assets/reference/hair/back-front/h-b07.jpg",
              image_rear: "/assets/reference/hair/back-rear/h-b07.jpg",
            },
            why: "비대칭이라 턱 부각 덜함. 레이어드로 하관 가벼움. 비대칭 앞머리 + 가벼운 뒷머리 = 시원하고 세련된 조화.",
            axis_shift: {},
            salon_instruction: "",
            trend: null,
          },
        ],
        avoid: [],
        catalog: {
          front: [
            { id: "h-f01", name_kr: "풀뱅", name_en: "Full Bangs", image: "/assets/reference/hair/front/h-f01.jpg" },
            { id: "h-f02", name_kr: "시스루뱅", name_en: "See-Through Bangs", image: "/assets/reference/hair/front/h-f02.jpg" },
            { id: "h-f03", name_kr: "5:5 사이드뱅", name_en: "Center-Parted Side Bangs", image: "/assets/reference/hair/front/h-f03.jpg" },
            { id: "h-f04", name_kr: "비대칭 사이드뱅", name_en: "Asymmetric Side Bangs", image: "/assets/reference/hair/front/h-f04.jpg" },
            { id: "h-f05", name_kr: "턱선길이 사이드뱅", name_en: "Jaw-Length Side Bangs", image: "/assets/reference/hair/front/h-f05.jpg" },
            { id: "h-f06", name_kr: "컬리뱅", name_en: "Curly Bangs", image: "/assets/reference/hair/front/h-f06.jpg" },
            { id: "h-f07", name_kr: "처피뱅", name_en: "Choppy Bangs", image: "/assets/reference/hair/front/h-f07.jpg" },
            { id: "h-f08", name_kr: "앞머리없음", name_en: "No Bangs", image: "/assets/reference/hair/front/h-f08.jpg" },
          ],
          back: [
            { id: "h-b01", name_kr: "숏컷", name_en: "Short Pixie Cut", image_front: "/assets/reference/hair/back-front/h-b01.jpg", image_rear: "/assets/reference/hair/back-rear/h-b01.jpg" },
            { id: "h-b02", name_kr: "보브단발/레이어드", name_en: "Bob Cut / Layered", image_front: "/assets/reference/hair/back-front/h-b02.png", image_rear: "/assets/reference/hair/back-rear/h-b02.jpg" },
            { id: "h-b03", name_kr: "칼단발", name_en: "Blunt Bob", image_front: "/assets/reference/hair/back-front/h-b03.jpg", image_rear: "/assets/reference/hair/back-rear/h-b03.jpg" },
            { id: "h-b04", name_kr: "단발 굵은펌", name_en: "Short C-Curl Perm", image_front: "/assets/reference/hair/back-front/h-b04.jpg", image_rear: "/assets/reference/hair/back-rear/h-b04.jpg" },
            { id: "h-b05", name_kr: "단발 S컬펌", name_en: "Short S-Curl Perm", image_front: "/assets/reference/hair/back-front/h-b05.jpg", image_rear: "/assets/reference/hair/back-rear/h-b05.jpg" },
            { id: "h-b06", name_kr: "일자 중단발", name_en: "Medium Straight", image_front: "/assets/reference/hair/back-front/h-b06.jpg", image_rear: "/assets/reference/hair/back-rear/h-b06.jpg" },
            { id: "h-b07", name_kr: "중단발 레이어드", name_en: "Medium Layered", image_front: "/assets/reference/hair/back-front/h-b07.jpg", image_rear: "/assets/reference/hair/back-rear/h-b07.jpg" },
            { id: "h-b08", name_kr: "중단발 아웃C컬", name_en: "Medium Outward C-Curl", image_front: "/assets/reference/hair/back-front/h-b08.jpg", image_rear: "/assets/reference/hair/back-rear/h-b08.png" },
            { id: "h-b09", name_kr: "중단발펌", name_en: "Medium S-Curl Perm", image_front: "/assets/reference/hair/back-front/h-b09.jpg", image_rear: "/assets/reference/hair/back-rear/h-b09.jpg" },
            { id: "h-b10", name_kr: "긴 생머리", name_en: "Long Straight", image_front: "/assets/reference/hair/back-front/h-b10.jpg", image_rear: "/assets/reference/hair/back-rear/h-b10.jpg" },
            { id: "h-b11", name_kr: "긴머리펌", name_en: "Long Wave Perm", image_front: "/assets/reference/hair/back-front/h-b11.jpg", image_rear: "/assets/reference/hair/back-rear/h-b11.jpg" },
            { id: "h-b12", name_kr: "긴머리 레이어드펌", name_en: "Long Layered Perm", image_front: "/assets/reference/hair/back-front/h-b12.jpg", image_rear: "/assets/reference/hair/back-rear/h-b12.png" },
            { id: "h-b13", name_kr: "히피펌", name_en: "Hippie Perm", image_front: "/assets/reference/hair/back-front/h-b13.jpg", image_rear: "/assets/reference/hair/back-rear/h-b13.jpg" },
          ],
        },
      },
    },
    {
      id: "action_plan",
      locked: false,
      unlock_level: "full",
      teaser: { categories: ["턱선", "콧대", "눈썹 끝"] },
      content: {
        items: [
          {
            category: "턱선",
            priority: "핵심 포인트",
            recommendations: [
              {
                action:
                  "부드러운 얼굴형에 또렷한 윤곽선을 만들어 카리스마를 더해줍니다. 턱선을 따라 자연스럽게 음영을 넣어 정돈된 인상을 연출하세요.",
                expected_effect: "더 또렷한 골격으로",
              },
            ],
          },
          {
            category: "콧대",
            priority: "핵심 포인트",
            recommendations: [
              {
                action:
                  "얼굴 중심축을 강조해 전체적으로 입체감 있는 인상을 만듭니다. 코등 라인을 밝게 해서 세련된 느낌을 더하세요.",
                expected_effect: "더 강렬한 존재감으로",
              },
            ],
          },
          {
            category: "눈썹 끝",
            priority: "추가하면 좋은 포인트",
            recommendations: [
              {
                action:
                  "부드러운 인상에 선명함을 더해주는 포인트입니다. 눈썹 끝을 또렷하게 그려 강렬한 눈빛을 연출하세요.",
                expected_effect: "더 또렷한 골격으로",
              },
            ],
          },
          {
            category: "눈두덩",
            priority: "추가하면 좋은 포인트",
            recommendations: [
              {
                action:
                  "눈두덩에 깊이를 더해 깊은 눈매를 만듭니다. 자연스러운 그림자 효과로 신비로운 매력을 연출하세요.",
                expected_effect: "더 또렷한 느낌으로",
              },
            ],
          },
        ],
      },
    },
    {
      id: "type_reference",
      locked: false,
      unlock_level: "full",
      teaser: { headline: "'부드러운 카리스마' 유형과 65% 유사" },
      content: {
        type_name: "부드러운 카리스마",
        type_id: 6,
        similarity: 65,
        reasons: [
          "얼굴 구조의 주요 특징이 '부드러운 카리스마' 유형 경향과 맞아요.",
          "골격 축에서 또렷한 쪽 경향이 뚜렷해요.",
          "현재 이미지의 비율, 각도, 인상이 이 유형의 전형적 특징과 잘 연결돼요.",
        ],
        styling_tips: [
          "부드러운 카리스마 유형의 장점을 살리면서 변화를 주는 게 포인트예요.",
          "윤곽을 또렷하게 잡아주는 하이라이트가 효과적이에요.",
          "특히 턱선, 콧대 부분에 집중하면 변화가 빠르게 느껴져요.",
        ],
        runner_ups: [
          { type_name: "날카로운 카리스마", type_id: 8, similarity: 62 },
          { type_name: "사랑스러운 인형", type_id: 2, similarity: 58 },
        ],
      },
    },
    {
      id: "trend_context",
      locked: false,
      unlock_level: "full",
      teaser: null,
      content: {
        trends: [
          {
            title: "적용 가이드",
            description:
              "리포트에서 가장 변화가 큰 포인트는 턱선, 콧대 부분이에요. 하나씩 순서대로 적용해보면서 자신에게 맞는 강도를 찾아보세요. 처음엔 가볍게 시작하고, 익숙해지면 점차 강도를 올리는 게 자연스러워요.",
          },
        ],
      },
    },
  ],
  paywall: {
    standard: {
      price: 2900,
      original_price: 5000,
      label: "\u20A92,900 잠금 해제",
      method: "manual",
    },
    full: {
      price: 26100,
      original_price: 44000,
      label: "+\u20A926,100 잠금 해제",
      total_note: "이전 결제 포함 총 \u20A929,000",
      method: "manual",
    },
  },
  payment_account: {
    bank: "카카오뱅크",
    number: "3333-00-0000000",
    holder: "홍한진(시각)",
    kakao_link: "kakaotalk://send?",
  },
};
